# v2系では文字列での指定が推奨されます
version: '2'

run:
    timeout: 5m
    modules-download-mode: readonly

linters:
    enable:
        - gocritic
        - misspell
        - revive
        - errcheck
        - staticcheck

    settings:
        gocritic:
            enabled-tags:
                - diagnostic
                - experimental
                - opinionated
                - performance
                - style
        revive:
            rules:
                - name: exported
                  disabled: true
                - name: package-comments
                  disabled: true
        errcheck:
            check-type-assertions: true

issues:
    new-from-merge-base: main
    whole-files: true
    max-issues-per-linter: 0
    max-same-issues: 0
